# It contains the default values for training a FastConformer-Hybrid-Transducer-CTC ASR model (~110M params) with sub-word encoding.
# The model has two decoders: RNNT (Transducer) and CTC.

name: "FastConformer-Hybrid-TDT-CTC-BPE-110M"

# Optionally initialize parts of the model from a pre-trained NeMo .nemo checkpoint
# (for example: parakeet-tdt_ctc-110m). Provide a real path before training.
init_from_nemo_model:
  model0:
    path: ???
    # Initialize encoder/preprocessor, but start fresh decoders/joint
    exclude: ["decoder", "joint", "aux_ctc"]

model:
  sample_rate: 16000
  compute_eval_loss: false  # Disable transducer loss during validation to save memory on long samples
  log_prediction: true
  skip_nan_grad: false

  model_defaults:
    enc_hidden: ${model.encoder.d_model}
    pred_hidden: 640
    joint_hidden: 640
    tdt_durations: [0, 1, 2, 3, 4]
    num_tdt_durations: 5

  train_ds:
    manifest_filepath: ???
    sample_rate: ${model.sample_rate}
    batch_size: 16  # increase if memory allows
    shuffle: true
    num_workers: 8
    pin_memory: true
    max_duration: 40  # tune to your dataset
    min_duration: 0.1
    # tarred datasets
    is_tarred: false
    tarred_audio_filepaths: null
    shuffle_n: 2048
    # bucketing params
    bucketing_strategy: "synced_randomized"
    bucketing_batch_size: null

  validation_ds:
    manifest_filepath: ???
    sample_rate: ${model.sample_rate}
    batch_size: 16
    shuffle: false
    use_start_end_token: false
    num_workers: 8
    pin_memory: true

  test_ds:
    manifest_filepath: null
    sample_rate: ${model.sample_rate}
    batch_size: 16
    shuffle: false
    use_start_end_token: false
    num_workers: 8
    pin_memory: true

  # Train or point to a tokenizer directory containing `tokenizer.model` (bpe) or `vocab.txt` (wpe)
  # Do not add explicit vocabulary mappings here.
  tokenizer:
    dir: ???
    type: bpe  # bpe (SentencePiece) or wpe (WordPiece)

  preprocessor:
    _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
    sample_rate: ${model.sample_rate}
    normalize: "per_feature"
    window_size: 0.025
    window_stride: 0.01
    window: "hann"
    features: 80
    n_fft: 512
    frame_splicing: 1
    dither: 0.00001
    pad_to: 0

  spec_augment:
    _target_: nemo.collections.asr.modules.SpectrogramAugmentation
    freq_masks: 2
    time_masks: 10
    freq_width: 27
    time_width: 0.05

  encoder:
    _target_: nemo.collections.asr.modules.ConformerEncoder
    feat_in: ${model.preprocessor.features}
    feat_out: -1
    n_layers: 17
    d_model: 512

    # Sub-sampling parameters
    subsampling: dw_striding  # vggnet, striding, stacking, stacking_norm, dw_striding
    subsampling_factor: 8     # power of 2 for striding/vggnet
    subsampling_conv_channels: 256
    causal_downsampling: false

    # Optional extra reduction layer (set to null to disable)
    reduction: null
    reduction_position: null
    reduction_factor: 1

    # Feed-forward module
    ff_expansion_factor: 4

    # Attention module
    self_attention_model: rel_pos
    n_heads: 8
    att_context_size: [-1, -1]
    att_context_style: regular
    xscaling: true
    untie_biases: true
    pos_emb_max_len: 5000

    # Convolution module
    conv_kernel_size: 9
    conv_norm_type: batch_norm
    conv_context_size: null

    # Dropouts
    dropout: 0.1
    dropout_pre_encoder: 0.1
    dropout_emb: 0.0
    dropout_att: 0.1

    # Stochastic depth (disabled by default)
    stochastic_depth_drop_prob: 0.0
    stochastic_depth_mode: linear
    stochastic_depth_start_layer: 1

  decoder:
    _target_: nemo.collections.asr.modules.RNNTDecoder
    normalization_mode: null
    random_state_sampling: false
    blank_as_pad: true
    prednet:
      pred_hidden: ${model.model_defaults.pred_hidden}
      pred_rnn_layers: 1
      t_max: null
      dropout: 0.2

  joint:
    _target_: nemo.collections.asr.modules.RNNTJoint
    log_softmax: null
    preserve_memory: false
    fuse_loss_wer: true
    fused_batch_size: 4
    jointnet:
      joint_hidden: ${model.model_defaults.joint_hidden}
      activation: relu
      dropout: 0.2
    num_extra_outputs: ${model.model_defaults.num_tdt_durations}

  decoding:
    strategy: greedy_batch  # greedy, greedy_batch, beam, tsd, alsd
    model_type: tdt
    durations: ${model.model_defaults.tdt_durations}
    greedy:
      max_symbols: 10
    beam:
      beam_size: 2
      return_best_hypothesis: false
      score_norm: true
      tsd_max_sym_exp: 50
      alsd_max_target_len: 2.0

  aux_ctc:
    ctc_loss_weight: 0.3
    use_cer: false
    ctc_reduction: mean_batch
    decoder:
      _target_: nemo.collections.asr.modules.ConvASRDecoder
      feat_in: null
      num_classes: -1
      vocabulary: []
    decoding:
      strategy: greedy

  interctc:
    loss_weights: []
    apply_at_layers: []

  loss:
    loss_name: tdt
    tdt_kwargs:
      fastemit_lambda: 0.0
      clamp: -1.0
      durations: ${model.model_defaults.tdt_durations}
      sigma: 0.02
      omega: 0.1

  optim:
    name: adamw
    lr: 6e-4
    betas: [0.9, 0.98]
    weight_decay: 1e-3
    sched:
      name: CosineAnnealing
      warmup_steps: null
      warmup_ratio: 0.1
      min_lr: 1e-6

trainer:
  devices: -1
  num_nodes: 1
  max_epochs: 500
  max_steps: -1
  val_check_interval: 1.0
  accelerator: auto
  strategy:
    _target_: lightning.pytorch.strategies.DDPStrategy
    gradient_as_bucket_view: true
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  precision: 32  # 16, 32, or bf16
  log_every_n_steps: 10
  enable_progress_bar: true
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 1
  sync_batchnorm: true
  enable_checkpointing: false
  logger: false
  benchmark: false

exp_manager:
  exp_dir: null
  name: ${name}
  create_tensorboard_logger: true
  create_checkpoint_callback: true
  checkpoint_callback_params:
    monitor: "val_wer"
    mode: "min"
    save_top_k: 5
    always_save_nemo: true
  resume_from_checkpoint: null
  resume_if_exists: false
  resume_ignore_no_checkpoint: false
  create_wandb_logger: false
  wandb_logger_kwargs:
    name: null
    project: null
